services:
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "curtin_db:/data/db"
  redis:
    image: redis:7.4.5-alpine3.21
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  curtin_db:
